const state={cases:[],current:null,tab:'plan'};const $=s=>document.querySelector(s);const uid=p=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok){const e=new Error(data.error?.message||'请求失败');e.code=data.error?.code;e.details=data.error?.details;throw e}return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
async function loadCases(){const data=await api('/api/v1/rigging-cases');state.cases=data.items;renderList();$('#connection').textContent='服务正常'}
function renderList(){$('#case-list').innerHTML=state.cases.map(c=>`<button class="case-item ${state.current?.case.id===c.id?'active':''}" data-id="${c.id}"><strong>${escapeHTML(c.showName)}</strong><span>${c.status} · v${c.version}</span></button>`).join('');document.querySelectorAll('.case-item').forEach(b=>b.onclick=()=>openCase(b.dataset.id))}
async function openCase(id){state.current=await api(`/api/v1/rigging-cases/${id}`);$('#empty').hidden=true;$('#case-view').hidden=false;render();renderList()}
function render(){const c=state.current.case;$('#case-title').textContent=c.showName;$('#case-owner').textContent=`负责人 ${c.owner} · 场地限制 ${c.venueLimitKg} kg`;$('#case-time').textContent=`计划开演 ${new Date(c.scheduledAt).toLocaleString()}`;$('#case-status').textContent=c.status;$('#case-version').textContent=`version ${c.version}`;renderTabs();$('#points').innerHTML=c.loadPoints.map(p=>`<div class="item"><strong>${p.id}</strong>${p.equipmentCode}<span class="badge">${p.parentPointId?`父 ${p.parentPointId} · `:''}${p.staticLoadKg}kg × ${(p.dynamicFactorPermille/1000).toFixed(2)} / ${p.ratedCapacityKg}kg · r${p.revision}</span></div>`).join('');$('#cues').innerHTML=c.cues.map(q=>`<div class="item"><strong>${q.sequence}. ${q.id}</strong>${escapeHTML(q.action)}<span class="badge">${q.equipmentCodes.join(', ')} · r${q.revision}</span></div>`).join('');renderFindings();renderRun();renderAttempts();renderReview();renderAudit()}
function renderTabs(){document.querySelectorAll('#steps button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==`tab-${state.tab}`)}
function renderFindings(){const c=state.current.case,fs=c.findings;$('#findings').innerHTML=fs.length?fs.map(f=>`<div class="finding ${f.severity==='BLOCKING'?'blocking':'warning'}"><strong>${f.ruleCode}</strong> · ${f.message}<span class="badge">${f.status}</span><div class="muted">依据：${f.source} / 影响 ${f.affectedRefs.join(', ')}</div></div>`).join(''):'<p class="muted">尚未产生校验问题。</p>';const latest=c.validationBatches?.at(-1);if(latest){const count=s=>latest.issues.filter(x=>x.state===s).length;$('#batch-summary').innerHTML=`<div class="item"><strong>最近批次 ${latest.id}</strong><span class="badge">${latest.stale?'已过期':'有效'}</span><div class="muted">输入 v${latest.aggregateVersion} · 新增 ${count('NEW')} · 持续 ${count('PERSISTING')} · 已消除 ${count('RESOLVED')}${latest.changedRefs?.length?` · 变化 ${latest.changedRefs.join(', ')}`:''}</div></div>`}else $('#batch-summary').innerHTML='<p class="muted">尚未运行校验。</p>';const open=fs.filter(f=>f.severity==='BLOCKING'&&f.status==='OPEN');$('#remediation-form select').innerHTML=open.map(f=>`<option value="${f.id}" data-source="${f.source}">${f.ruleCode} · ${f.message}</option>`).join('')}
function renderRun(){const c=state.current.case,run=c.rehearsals.at(-1);$('#start-run').disabled=c.status!=='VALIDATED';if(!run||run.outcome!=='PENDING'){$('#run-form').innerHTML='<p class="muted">没有进行中的排练。</p>';return}const saved=Object.fromEntries(run.cueResults.map(x=>[x.cueId,x]));$('#run-form').innerHTML=c.cues.map(q=>{const r=saved[q.id]||{};return `<div class="result-row" data-cue="${q.id}"><strong>${q.sequence}. ${q.id}</strong><label><input class="success" type="checkbox" ${r.success!==false?'checked':''}>成功</label><input class="peak" type="number" min="0" value="${r.peakKg??''}" placeholder="峰值 kg"><input class="deviation" value="${escapeHTML(r.deviation||'')}" placeholder="偏差"><input class="evidence" value="${escapeHTML(r.evidence||'')}" placeholder="证据"><button type="button" class="save-cue">${r.updatedAt?'修正':'暂存'}</button><span class="badge">${r.updatedAt?'已录':'待录'}</span></div>`}).join('')+'<button class="primary">汇总已保存结果并完成排练</button>'}
function renderAttempts(){const items=state.current.case.remediationAttempts||[];$('#attempts').innerHTML=items.slice().reverse().map(a=>`<div class="item"><strong>${a.recheckType} · ${a.passed?'通过':'失败'}</strong>${escapeHTML(a.conclusion)}<span class="badge">${new Date(a.submittedAt).toLocaleString()}</span></div>`).join('')}
function renderReview(){const c=state.current.case;const open=c.findings.filter(f=>f.status==='OPEN'&&f.severity==='BLOCKING').length;$('#review-checklist').innerHTML=`<div class="item">载荷与提示已编制 <span class="badge">${c.loadPoints.length} 吊点 / ${c.cues.length} 提示</span></div><div class="item">排练已完成 <span class="badge">${c.rehearsals.some(r=>r.outcome==='PASSED')?'是':'否'}</span></div><div class="item">未关闭阻断问题 <span class="badge">${open}</span></div>`;$('#release-form button').disabled=c.status!=='READY_FOR_REVIEW'}
function renderAudit(){const c=state.current.case;const cert=c.certificate;$('#certificate').innerHTML=cert?`<div class="certificate"><p class="eyebrow">RELEASE CERTIFICATE #${cert.serial}</p><h3>${cert.id}</h3><p>冻结版本 v${cert.frozenVersion} · 复核员 ${escapeHTML(cert.reviewer)}</p><p class="digest">快照 ${cert.snapshotDigest}</p><p>快照摘要：${state.current.snapshotValid?'通过':'失败'} · 审计链：${state.current.auditChainValid?'通过':'失败'}</p><button id="verify-cert">重新校验</button></div>`:'<p class="muted">方案放行后将在此显示不可变凭据。</p>';$('#timeline').innerHTML=state.current.timeline.map(e=>`<div class="event"><strong>${e.sequence}. ${e.kind}</strong><span class="badge">v${e.aggregateVersion}</span><div class="muted">${new Date(e.occurredAt).toLocaleString()}</div><div class="digest">${e.digest}</div></div>`).join('');if(cert)$('#verify-cert').onclick=async()=>toast((await api(`/api/v1/rigging-cases/${c.id}/certificate/verify`)).valid?'摘要校验通过':'摘要校验失败')}
function meta(){return{expectedVersion:state.current.case.version,idempotencyKey:uid('web')}}async function write(path,method,body){try{const c=await api(path,{method,body:JSON.stringify(body)});await openCase(c.id);toast('操作已保存')}catch(e){if(state.current)await openCase(state.current.case.id);const items=e.details?.items;toast(items?.length?`${e.message}：${items.map(x=>`${x.businessId||x.index} ${x.message}`).join('；')}`:e.message);throw e}}
$('#new-case').onclick=()=>$('#create-dialog').showModal();$('#cancel-create').onclick=()=>$('#create-dialog').close();$('#create-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const c=await api('/api/v1/rigging-cases',{method:'POST',body:JSON.stringify({showName:f.get('showName'),venueLimitKg:+f.get('venueLimitKg'),owner:f.get('owner'),scheduledAt:new Date(f.get('scheduledAt')).toISOString(),idempotencyKey:uid('create')})});$('#create-dialog').close();await loadCases();await openCase(c.id)};
$('#steps').onclick=e=>{if(e.target.dataset.tab){state.tab=e.target.dataset.tab;renderTabs()}};$('#point-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await write(`/api/v1/rigging-cases/${state.current.case.id}/load-points`,'PUT',{...meta(),id:f.get('id'),equipmentCode:f.get('equipmentCode'),ratedCapacityKg:+f.get('ratedCapacityKg'),staticLoadKg:+f.get('staticLoadKg'),dynamicFactorPermille:+f.get('dynamicFactorPermille')});e.target.reset()};
$('#cue-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await write(`/api/v1/rigging-cases/${state.current.case.id}/cues`,'PUT',{...meta(),id:f.get('id'),sequence:+f.get('sequence'),action:f.get('action'),equipmentCodes:f.get('equipmentCodes').split(',').map(x=>x.trim()).filter(Boolean),mutexGroup:f.get('mutexGroup'),expectedDurationMs:+f.get('expectedDurationMs')});e.target.reset()};
$('#changeset-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),lines=v=>String(v||'').split('\n').map(x=>x.trim()).filter(Boolean).map(x=>x.split(',').map(y=>y.trim()));const loadPoints=lines(f.get('loadPoints')).map(x=>({id:x[0]||'',equipmentCode:x[1]||'',parentPointId:x[2]||null,ratedCapacityKg:+x[3],staticLoadKg:+x[4],dynamicFactorPermille:+x[5]}));const cues=lines(f.get('cues')).map(x=>({id:x[0]||'',sequence:+x[1],action:x[2]||'',equipmentCodes:(x[3]||'').split('|').map(y=>y.trim()).filter(Boolean),mutexGroup:x[4]||'',expectedDurationMs:+x[5]}));await write(`/api/v1/rigging-cases/${state.current.case.id}/change-sets`,'POST',{...meta(),loadPoints,cues});e.target.reset()};
$('#validate').onclick=()=>write(`/api/v1/rigging-cases/${state.current.case.id}/validate`,'POST',meta());$('#start-run').onclick=()=>write(`/api/v1/rigging-cases/${state.current.case.id}/rehearsals`,'POST',{...meta(),operator:state.current.case.owner});
$('#run-form').onclick=async e=>{if(!e.target.classList.contains('save-cue'))return;const row=e.target.closest('.result-row'),run=state.current.case.rehearsals.at(-1);await write(`/api/v1/rigging-cases/${state.current.case.id}/rehearsals/${run.id}/cue-results/${row.dataset.cue}`,'PUT',{...meta(),success:row.querySelector('.success').checked,peakKg:+row.querySelector('.peak').value,deviation:row.querySelector('.deviation').value,evidence:row.querySelector('.evidence').value,operator:state.current.case.owner})};
$('#run-form').onsubmit=async e=>{e.preventDefault();const run=state.current.case.rehearsals.at(-1);await write(`/api/v1/rigging-cases/${state.current.case.id}/rehearsals/complete`,'POST',{...meta(),runId:run.id,results:[]})};
$('#remediation-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),finding=state.current.case.findings.find(x=>x.id===f.get('findingId')),body={...meta(),findingId:f.get('findingId'),revision:+f.get('revision'),note:f.get('note'),submittedBy:f.get('submittedBy')};if(finding?.source==='REHEARSAL')body.recheckInput={cueId:f.get('cueId'),success:f.get('success')==='on',peakKg:+f.get('peakKg'),deviation:f.get('success')==='on'?'':'重测失败',evidence:f.get('evidence')};await write(`/api/v1/rigging-cases/${state.current.case.id}/remediations`,'POST',body)};$('#release-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await write(`/api/v1/rigging-cases/${state.current.case.id}/release`,'POST',{...meta(),reviewer:f.get('reviewer')});state.tab='audit';render()};
$('#certificate-search').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),params=new URLSearchParams();if(f.get('serial'))params.set('serial',f.get('serial'));if(f.get('certificateID'))params.set('certificateID',f.get('certificateID'));try{const r=await api(`/api/v1/release-certificates?${params}`);$('#certificate-report').innerHTML=`<div class="certificate"><strong>${r.certificate.id} · #${r.certificate.serial}</strong><p>${escapeHTML(r.showName)} · ${r.caseStatus}</p>${r.checks.map(x=>`<div class="item"><strong>${x.name}</strong><span class="badge">${x.valid?'通过':'失败'}</span>${escapeHTML(x.detail)}</div>`).join('')}<p>总体：${r.valid?'通过':'失败'}${r.firstDamagedSequence?` · 首个损坏 sequence ${r.firstDamagedSequence}`:''}</p></div>`}catch(err){$('#certificate-report').innerHTML='';toast(err.message)}};
function escapeHTML(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}loadCases().catch(e=>{$('#connection').textContent='连接失败';toast(e.message)});
