package store

var schemaStatements = []string{
	`PRAGMA journal_mode=WAL`, `PRAGMA foreign_keys=ON`, `PRAGMA busy_timeout=5000`,
	`CREATE TABLE IF NOT EXISTS schema_version(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)`,
	`INSERT OR IGNORE INTO schema_version(version,applied_at) VALUES(1,CURRENT_TIMESTAMP)`,
	`CREATE TABLE IF NOT EXISTS rigging_cases(id TEXT PRIMARY KEY,show_name TEXT NOT NULL,venue_limit_kg INTEGER NOT NULL,owner TEXT NOT NULL,scheduled_at TEXT NOT NULL,status TEXT NOT NULL,version INTEGER NOT NULL,created_at TEXT NOT NULL,released_at TEXT)`,
	`CREATE TABLE IF NOT EXISTS load_points(id TEXT NOT NULL,case_id TEXT NOT NULL,equipment_code TEXT NOT NULL,parent_point_id TEXT,rated_capacity_kg INTEGER NOT NULL,static_load_kg INTEGER NOT NULL,dynamic_factor_permille INTEGER NOT NULL,revision INTEGER NOT NULL,PRIMARY KEY(case_id,id),UNIQUE(case_id,equipment_code),FOREIGN KEY(case_id) REFERENCES rigging_cases(id))`,
	`CREATE TABLE IF NOT EXISTS scene_cues(id TEXT NOT NULL,case_id TEXT NOT NULL,sequence_no INTEGER NOT NULL,action TEXT NOT NULL,equipment_codes TEXT NOT NULL,mutex_group TEXT NOT NULL,expected_duration_ms INTEGER NOT NULL,revision INTEGER NOT NULL,PRIMARY KEY(case_id,id),UNIQUE(case_id,sequence_no),FOREIGN KEY(case_id) REFERENCES rigging_cases(id))`,
	`CREATE TABLE IF NOT EXISTS safety_findings(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,source TEXT NOT NULL,rule_code TEXT NOT NULL,severity TEXT NOT NULL,message TEXT NOT NULL,affected_refs TEXT NOT NULL,observed_revisions TEXT NOT NULL,status TEXT NOT NULL,remediation_revision INTEGER,closed_at TEXT,FOREIGN KEY(case_id) REFERENCES rigging_cases(id))`,
	`CREATE TABLE IF NOT EXISTS rehearsal_runs(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT,cue_results TEXT NOT NULL,operator TEXT NOT NULL,outcome TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES rigging_cases(id))`,
	`CREATE TABLE IF NOT EXISTS validation_batches(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,aggregate_version INTEGER NOT NULL,started_at TEXT NOT NULL,completed_at TEXT NOT NULL,final_status TEXT NOT NULL,stale INTEGER NOT NULL,changed_refs TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES rigging_cases(id))`,
	`CREATE INDEX IF NOT EXISTS validation_batches_case_time ON validation_batches(case_id,completed_at DESC,id)`,
	`CREATE TABLE IF NOT EXISTS validation_batch_inputs(batch_id TEXT NOT NULL,ref TEXT NOT NULL,revision INTEGER NOT NULL,PRIMARY KEY(batch_id,ref),FOREIGN KEY(batch_id) REFERENCES validation_batches(id))`,
	`CREATE TABLE IF NOT EXISTS validation_batch_issues(batch_id TEXT NOT NULL,identity TEXT NOT NULL,rule_code TEXT NOT NULL,severity TEXT NOT NULL,message TEXT NOT NULL,affected_refs TEXT NOT NULL,state TEXT NOT NULL,PRIMARY KEY(batch_id,identity),FOREIGN KEY(batch_id) REFERENCES validation_batches(id))`,
	`CREATE TABLE IF NOT EXISTS remediation_attempts(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,finding_id TEXT NOT NULL,observed_revisions TEXT NOT NULL,note TEXT NOT NULL,submitted_by TEXT NOT NULL,submitted_at TEXT NOT NULL,recheck_type TEXT NOT NULL,recheck_input TEXT,passed INTEGER NOT NULL,conclusion TEXT NOT NULL,FOREIGN KEY(case_id) REFERENCES rigging_cases(id),FOREIGN KEY(finding_id) REFERENCES safety_findings(id))`,
	`CREATE TABLE IF NOT EXISTS audit_events(case_id TEXT NOT NULL,sequence_no INTEGER NOT NULL,kind TEXT NOT NULL,aggregate_version INTEGER NOT NULL,payload BLOB NOT NULL,previous_digest TEXT NOT NULL,digest TEXT NOT NULL UNIQUE,occurred_at TEXT NOT NULL,PRIMARY KEY(case_id,sequence_no),FOREIGN KEY(case_id) REFERENCES rigging_cases(id))`,
	`CREATE TABLE IF NOT EXISTS idempotency_records(scope TEXT NOT NULL,key TEXT NOT NULL,response BLOB NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(scope,key))`,
	`CREATE TABLE IF NOT EXISTS release_certificates(id TEXT PRIMARY KEY,case_id TEXT NOT NULL UNIQUE,serial INTEGER NOT NULL UNIQUE,frozen_version INTEGER NOT NULL,snapshot_digest TEXT NOT NULL,audit_head_digest TEXT NOT NULL,reviewer TEXT NOT NULL,issued_at TEXT NOT NULL,snapshot BLOB NOT NULL,FOREIGN KEY(case_id) REFERENCES rigging_cases(id))`,
	`INSERT OR IGNORE INTO schema_version(version,applied_at) VALUES(2,CURRENT_TIMESTAMP)`,
	`CREATE TRIGGER IF NOT EXISTS released_case_immutable BEFORE UPDATE ON rigging_cases WHEN OLD.status='RELEASED' BEGIN SELECT RAISE(ABORT,'released case is immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS released_case_no_delete BEFORE DELETE ON rigging_cases WHEN OLD.status='RELEASED' BEGIN SELECT RAISE(ABORT,'released case cannot be deleted'); END`,
	`CREATE TRIGGER IF NOT EXISTS certificate_no_update BEFORE UPDATE ON release_certificates BEGIN SELECT RAISE(ABORT,'certificate is immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS certificate_no_delete BEFORE DELETE ON release_certificates BEGIN SELECT RAISE(ABORT,'certificate cannot be deleted'); END`,
	`CREATE TRIGGER IF NOT EXISTS validation_batch_no_delete BEFORE DELETE ON validation_batches BEGIN SELECT RAISE(ABORT,'validation batch cannot be deleted'); END`,
	`CREATE TRIGGER IF NOT EXISTS validation_batch_core_immutable BEFORE UPDATE ON validation_batches WHEN OLD.case_id<>NEW.case_id OR OLD.aggregate_version<>NEW.aggregate_version OR OLD.started_at<>NEW.started_at OR OLD.completed_at<>NEW.completed_at OR OLD.final_status<>NEW.final_status BEGIN SELECT RAISE(ABORT,'validation batch core is immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS validation_batch_input_no_update BEFORE UPDATE ON validation_batch_inputs BEGIN SELECT RAISE(ABORT,'validation batch input is immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS validation_batch_input_no_delete BEFORE DELETE ON validation_batch_inputs BEGIN SELECT RAISE(ABORT,'validation batch input cannot be deleted'); END`,
	`CREATE TRIGGER IF NOT EXISTS validation_batch_issue_no_update BEFORE UPDATE ON validation_batch_issues BEGIN SELECT RAISE(ABORT,'validation batch issue is immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS validation_batch_issue_no_delete BEFORE DELETE ON validation_batch_issues BEGIN SELECT RAISE(ABORT,'validation batch issue cannot be deleted'); END`,
	`CREATE TRIGGER IF NOT EXISTS remediation_attempt_no_update BEFORE UPDATE ON remediation_attempts BEGIN SELECT RAISE(ABORT,'remediation attempt is immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS remediation_attempt_no_delete BEFORE DELETE ON remediation_attempts BEGIN SELECT RAISE(ABORT,'remediation attempt cannot be deleted'); END`,
}
